name: edge-gateway
on:
  push:
    branches:
      - main
    paths:
      - 'packages/edge-gateway/**'
      - '.github/workflows/edge-gateway.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'packages/edge-gateway/**'
      - '.github/workflows/edge-gateway.yml'
      - 'pnpm-lock.yaml'
jobs:
  check:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build:edge-gateway
      - name: Lint
        run: pnpm lint
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test:edge-gateway
  deploy-staging:
    name: Deploy Staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - name: Publish app
        uses: cloudflare/wrangler-action@v3
        env:
          ENV: 'staging' # inform the build process what the env is
          SENTRY_TOKEN: ${{secrets.SENTRY_TOKEN}}
          SENTRY_UPLOAD: ${{ secrets.SENTRY_UPLOAD }}
        with:
          apiToken: ${{secrets.CF_GATEWAY_TOKEN }}
          workingDirectory: 'packages/edge-gateway'
          environment: 'staging'
  changelog:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Release
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.tag-release.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: tag-release
        with:
          path: packages/edge-gateway
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          monorepo-tags: true
          package-name: edge-gateway
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changelog.outputs.releases_created
    name: Release
    runs-on: ubuntu-latest
    needs:
      - check
      - test
      - changelog
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        env:
          ENV: 'production' # inform the build process what the env is
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
          SENTRY_UPLOAD: ${{ secrets.SENTRY_UPLOAD }}
        with:
          apiToken: ${{ secrets.CF_GATEWAY_TOKEN }}
          workingDirectory: 'packages/edge-gateway'
          environment: 'production'