name: ipfs-gateway-race
on:
  push:
    branches:
      - main
    paths:
      - 'packages/ipfs-gateway-race/**'
      - '.github/workflows/ipfs-gateway-race.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/ipfs-gateway-race/**'
      - '.github/workflows/ipfs-gateway-race.yml'
      - 'pnpm-lock.yaml'

jobs:
  check:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - name: Typecheck
        uses: gozala/typescript-error-reporter-action@v1.0.8
        with:
          project: packages/ipfs-gateway-race/tsconfig.json

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - name: Test
        run: pnpm --filter ipfs-gateway-race test

  changelog:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      releases_created: ${{ steps.tag-release.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: tag-release
        with:
          path: packages/ipfs-gateway-race
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changelog.outputs.releases_created
    name: Release
    runs-on: ubuntu-latest
    needs:
      - check
      - test
      - changelog
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - run: pnpm install
      - name: NPM Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        run: |
          cd packages/ipfs-gateway-race/dist
          npm publish --access=public
